### ISSUE TITLE
Move plotter from `src/hexapod` to `src/templates`

### ISSUE THREAD

**Issue by mithi** [mithi/hexapod#138]
Move this whole file to the `src/templates` directory. Update all dependents and dependencies. Make sure nothing is broken.
https://github.com/mithi/hexapod/blob/cdd2f1e89cf3b2a1bffb32c4769d2f6a917e8b35/src/hexapod/plotter.js

**Rationale** 
The hexapod subdirectory contains all the files to compute the orientations and points of the hexapod, 
it shouldn't be in charge of displaying the hexapod. Also we want to move a couple of steps forward to making the `hexapod` subdirectory it's own package / library which can be called by any application. 

https://github.com/mithi/hexapod/blob/cdd2f1e89cf3b2a1bffb32c4769d2f6a917e8b35/src/hexapod/plotter.js#L1-L100

**Comment by lashewi** [comment]
Can I work on this?

**Comment by mithi** [comment]
> Can I work on this?

Sure! Make sure nothing is broken!

**Comment by 2Shar18** [comment]
> Can I work on this?

Hey, have you started working on this? 
If not can I take this issue?

**Comment by mithi** [comment]
> > Can I work on this?
> 
> Hey, have you started working on this?
> If not can I take this issue?

Sure! Make sure you don't break anything! :D
