### ISSUE TITLE
Remove unused code, make sure this doesn't break anything

### ISSUE THREAD

**Issue by mithi** [mithi/hexapod#139]
Find unused code and remove code that are unnecessary

https://github.com/mithi/hexapod/blob/cdd2f1e89cf3b2a1bffb32c4769d2f6a917e8b35/src/templates/plotParams.js#L280-L287

https://github.com/mithi/hexapod/blob/cdd2f1e89cf3b2a1bffb32c4769d2f6a917e8b35/src/templates/plotParams.js#L9-L10

https://github.com/mithi/hexapod/blob/cdd2f1e89cf3b2a1bffb32c4769d2f6a917e8b35/src/hexapod/VirtualHexapod.js#L302-L307

**Comment by EllingtonK** [comment]
Hi mithi.  I am a first timer.  I would like to take up this issue.

**Comment by mithi** [comment]
> Hi mithi. I am a first timer. I would like to take up this issue.

Sure. Make sure your change doesn't break anything!

**Comment by mithi** [comment]
> Hi mithi. I am a first timer. I would like to take up this issue.

Sure, make sure it doesn't break anything!
You can also checkout the [contribution guidelines](https://github.com/mithi/hexapod/blob/master/CONTRIBUTING.md) and [commit styleguide!](https://github.com/mithi/hexapod/wiki/A-Commit-Style-Guide)

**Comment by EllingtonK** [comment]
Hi mithi.  I was going to work on this issue first.  I thought I would be able to download the zip into Apache Netbeans and run it, but it doesn't seem to run.  So I wanted to create a separate branch to work on editing the code, but it doesn't look like I'm allowed to add a branch.  Any suggestions?

**Comment by mithi** [comment]
> Hi mithi. I was going to work on this issue first. I thought I would be able to download the zip into Apache Netbeans and run it, but it doesn't seem to run. So I wanted to create a separate branch to work on editing the code, but it doesn't look like I'm allowed to add a branch. Any suggestions?

I don't know how apache netbeans work but you can work on it on your local machine or https://codesandbox.io/.

You can do follow the following steps
1. Fork the mithi/hexapod repository to your own account using the fork button on the top-right of the GitHub page.
2. Clone your repository and cd into it: `git clone https://github.com/username/hexapod.git`
3. Inside the directory, add upstream, ie: `git remote add upstream https://github.com/mithi/hexapod.git`
4. Create and checkout the branch you'd like to work on
```
$ git checkout master
$ git checkout -b your-branch-name
```
Commit and push as you like to your own fork
```
git push origin your-branch-name
```
See also: https://github.com/mithi/hexapod/wiki/Simple-Git-Workflow-guide

**Comment by EllingtonK** [comment]
OK, thank you.  I have it cloned correctly now.

**Comment by EllingtonK** [comment]
Hi mithi. I've modified the plotParams.js file and tried to run the Test Suite, but I'm not sure it's working.  The screen flashes for a few minutes, but nothing ever displays in the Test summary window.  I thought it was supposed to display a success or failure message for each test.   Am I missing something?


![image](https://user-images.githubusercontent.com/71473725/95689895-050a2f00-0be2-11eb-9929-131912ba65eb.png)

Also, I saw that there was a new commit to your branch, but when I try to fetch the changes and rebase, I get an error message.

![image](https://user-images.githubusercontent.com/71473725/95689924-3be04500-0be2-11eb-8326-9330257777f3.png)

**Comment by EllingtonK** [comment]
OK, the test suite issue appears to be a problem with my browser, not codesandbox.  I'm still not sure why I can't rebase though.

**Comment by mithi** [comment]
> OK, the test suite issue appears to be a problem with my browser, not codesandbox. I'm still not sure why I can't rebase though.

Hey, did you try

```
git remote add upstream https://github.com/mithi/hexapod.git
git fetch upstream
git checkout master
git rebase upstream/master
```

Interesting related readings
- https://gist.github.com/ravibhure/a7e0918ff4937c9ea1c456698dcd58aa
- https://blog.algolia.com/master-git-rebase/
- https://www.brad.net.nz/blog/2017/07/merging-a-git-repository-from-upstream-when-rebase-wont-work/

**Comment by mithi** [comment]
@EllingtonK 

After doing `git fetch upstream` Did you also try checking out your branch and doing `get rebase master` ?

**Comment by EllingtonK** [comment]
Yes, but something's still wrong.  It tells me the rebase is successful, but this is what I show when I try a git status.

![image](https://user-images.githubusercontent.com/71473725/96356296-66d30900-10ba-11eb-8eef-974d91ab03a4.png)

And on my github page I still show I'm behind.

![image](https://user-images.githubusercontent.com/71473725/96356316-92ee8a00-10ba-11eb-9cd9-4ed6de6f0e7f.png)

**Comment by mithi** [comment]
@EllingtonK 

do `git push --force`

**Comment by mithi** [comment]
> git push --force

@EllingtonK 


I suggest you do the exercises here: https://onlywei.github.io/explain-git-with-d3/
So that you get more familiar with how git works visually.

I also recommend you install the vscode plugin `git graph`

https://ardalis.com/git-graph-visualizes-branches-in-vs-code-for-free/

**Comment by EllingtonK** [comment]
OK thanks.

**Comment by mithi** [comment]
@EllingtonK Is is also good: https://learngitbranching.js.org/
