### ISSUE TITLE
algorithm verifycation

### ISSUE THREAD

**Issue by IverYangg** [mithi/hexapod#158]
may I ask whether this simulation can verify some algorithm like reinforcement learning?

**Comment by mithi** [comment]
> may I ask whether this simulation can verify some algorithm like reinforcement learning?

Sorry for the late reply 😞 
theoretically yes you can use this simulation to verify reinforcement learning algorithms.
Do keep in mind that by design the physics simulation of this app is the bare-minimum which might be too primitive for your use-case. Hope that clears things up. Thanks!
