### ISSUE TITLE
Rename params prop to be more descriptive for sliders and NumberInputFields

### ISSUE THREAD

**Issue by mithi** [mithi/hexapod#36]
- https://github.com/mithi/hexapod/blob/master/src/components/generic/Slider.js
- https://github.com/mithi/hexapod/blob/master/src/components/generic/NumberInputField.js

**Comment by nitesh-kumar-sharma** [comment]
[https://github.com/mithi/hexapod/blob/master/src/components/generic/InputField.js](https://github.com/mithi/hexapod/blob/master/src/components/generic/InputField.js) 
showing not page not found

**Comment by mithi** [comment]
@nitesh-kumar-sharma 

https://github.com/mithi/hexapod/blob/master/src/components/generic/NumberInputField.js

> https://github.com/mithi/hexapod/blob/master/src/components/generic/InputField.js
> showing not page not found

Thanks for reporting @nitesh-kumar-sharma 

Here's the updated link:

https://github.com/mithi/hexapod/blob/master/src/components/generic/NumberInputField.js
