### ISSUE TITLE
ValidityState is not working when passing any alphabet or character 

### ISSUE THREAD

**Issue by nitesh-kumar-sharma** [mithi/hexapod#66]
As per the observation found in `NumberInputField` => `handleChange() `method propagating the exception when pass any character in place of number it directly goes to float conversion that means validation not handled properly.

![image](https://user-images.githubusercontent.com/22424381/84953897-033bcd80-b112-11ea-8bf5-be90da50dffa.png)

**Comment by mithi** [comment]
Thanks for submitting this issue, I'll fix it right away. 😅

**Comment by mithi** [comment]
<img width="1135" alt="Screen Shot 2020-06-18 at 4 58 29 PM" src="https://user-images.githubusercontent.com/1670421/85000459-03c17c00-b185-11ea-8e62-c31d8d8cc5d5.png">

**Comment by mithi** [comment]
<img width="455" alt="Screen Shot 2020-06-18 at 7 12 42 PM" src="https://user-images.githubusercontent.com/1670421/85013895-eb0e9180-b197-11ea-99c4-e21263f340a3.png">
<img width="461" alt="Screen Shot 2020-06-18 at 7 12 55 PM" src="https://user-images.githubusercontent.com/1670421/85013909-f1047280-b197-11ea-9b13-f2422c276886.png">
