### ISSUE TITLE
Sanity checks of parameters?

### ISSUE THREAD

**Issue by mithi** [mithi/hexapod#95]
https://github.com/mithi/hexapod/blob/dbd772cad6955378c07322e557511d4f13b35b94/src/hexapod/solvers/ik/hexapodSolver.js#L13-L20

Add check.

that tx, ty, tz are between -1 and 1,
rx, ry, rz, hipStance and legStance are within what is specified in 

https://github.com/mithi/hexapod/blob/master/src/components/vars.js

We can return null (early exit) or throw and error

**Comment by robintom** [comment]
Hi @mithi Could you please assign this to me ? I will work on this

**Comment by mithi** [comment]
@robintom sure! Don't forget to write tests! :)

**Comment by mithi** [comment]
> Hi @mithi Could you please assign this to me ? I will work on this

@robintom Sure! Don't forget to write tests!
